version: "3"
services:


    redis:
        image: redis:alpine
        networks:
            - app-network
    app:
        build:
            context: app
            args:
                PRODUCTION: 0


        privileged: true
        entrypoint: "yarn run dev"
        #env_file:
         #   - web-variables.env

        volumes:
            - ../:/project

        ports:
            - 3010:3000
            - 3011:3011
            - 3012:3012

        networks:
            - app-network

networks:
    app-network:

